# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'1.21.3'

In [5]:
np.__config__

<module 'numpy.__config__' from '/Users/josh/miniforge3/envs/myenv/lib/python3.8/site-packages/numpy/__config__.py'>

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
arr.nbytes

80

or

In [8]:
arr.itemsize * len(arr)

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
arr[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.random(size=(3,3,3))

array([[[0.96840796, 0.43846401, 0.69824071],
        [0.32388065, 0.65582265, 0.30143507],
        [0.41211869, 0.76905249, 0.90746879]],

       [[0.16617283, 0.64460108, 0.75271009],
        [0.55945181, 0.50671246, 0.00829238],
        [0.76546291, 0.01201225, 0.78838212]],

       [[0.36398876, 0.3711459 , 0.00160855],
        [0.61963524, 0.15033782, 0.96628178],
        [0.99808386, 0.69553496, 0.54800291]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
arr = np.random.random(size=(10,10))
arr.min(), arr.max()

(0.00905200610866308, 0.994655823083169)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
np.random.random(30).mean()

0.5493262106438955

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
np.array([1, 1, 1, 1, 0, 1, 1, 1, 1]).reshape(3,3)

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
np.pad(np.arange(0, 4).reshape(2,2 ), 1)

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 2, 3, 0],
       [0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [40]:
0 * np.nan

nan

In [41]:
np.nan == np.nan

False

In [42]:
np.inf > np.nan

False

In [43]:
np.nan - np.nan

nan

In [44]:
np.nan in set([np.nan])

True

In [39]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
arr = np.ones((5,5))
np.fill_diagonal(arr, [1,1,2,3,4])
np.roll(arr, -1)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 3., 1., 1.],
       [1., 1., 1., 4., 1.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

Brilliant solution from online. Probably not what they intended...

In [22]:
np.indices((8,8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
np.tile(4*[1,0] + 4*[0,1], 4).reshape((8,8))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

If you mean standardising so that everything sums to 1:

In [25]:
arr = np.random.random((5,5))
row_sums = arr.sum(axis=1, keepdims=True)
arr /= row_sums
arr.sum(1)

array([1., 1., 1., 1., 1.])

Or if you mean the $L^p$ vector norm (as in `sklearn.preprocessing.normalize`):

In [26]:
arr = np.random.random((5,5))
row_sums = np.linalg.norm(arr, axis=1, keepdims=True)
arr /= row_sums

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
np.matmul(np.random.random((5,3)), np.random.random((3,2)))

array([[0.58265256, 1.0512696 ],
       [0.27793248, 1.09726932],
       [0.79296765, 1.34525323],
       [0.70919129, 0.8227295 ],
       [0.82177478, 0.79896051]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
arr = np.arange(0, 10)
arr[(arr >= 3) & (arr <= 8)] = 0

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [186]:
print(sum(range(5),-1))

9


In [187]:
from numpy import *

In [188]:
print(sum(range(5),-1))

10


🤯

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [30]:
Z = np.random.randint(1, 10, size=10)

In [31]:
Z**Z

array([    4,     4,    27,   256,   256,  3125, 46656, 46656,     1,
          27])

In [32]:
2 << Z >> 2

array([ 2,  2,  4,  8,  8, 16, 32, 32,  1,  4])

In [33]:
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False])

In [34]:
1j*Z

array([0.+2.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+6.j,
       0.+1.j, 0.+3.j])

In [35]:
Z/1/1

array([2., 2., 3., 4., 4., 5., 6., 6., 1., 3.])

In [67]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [68]:
np.array(0) / np.array(0)

/var/folders/lq/9x41x71n6tj6rhwv7hkqjrx80000gn/T/ipykernel_68376/873513115.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [69]:
np.array(0) // np.array(0)

/var/folders/lq/9x41x71n6tj6rhwv7hkqjrx80000gn/T/ipykernel_68376/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [36]:
np.array([np.nan]).astype(int).astype(float)

array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

"Round away from zero" is a rounding rule that says whether positive or negative, deal with ties in a way that goes further from zero. Different from regular np rounding which is based on nearest even number. Implementation (found online) is:

In [37]:
arr = (np.random.random(10) - 0.5) * 100
np.sign(arr) * np.floor(np.abs(arr)) + np.floor(2 * (np.abs(arr) % 1))

array([-33., -43.,  29.,   5., -10.,  30., -26.,  -3.,  48.,  15.])

#### 30. How to find common values between two arrays? (★☆☆)

In [38]:
arr1 = np.random.randint(1, 10, 5)
arr2 = np.random.randint(1, 10, 5)
set(arr1).intersection(arr2)

{8, 9}

Or, more numpyishly

In [39]:
np.intersect1d(arr1, arr2)

array([8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [40]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

or more drastically

In [ ]:
import warnings; warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [71]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/lq/9x41x71n6tj6rhwv7hkqjrx80000gn/T/ipykernel_68376/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [43]:
np.datetime64('today') - 1, np.datetime64('today'), np.datetime64('today') + 1

(numpy.datetime64('2022-07-31'),
 numpy.datetime64('2022-08-01'),
 numpy.datetime64('2022-08-02'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [44]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [45]:
a = np.arange(0, 10)
b = np.arange(0, 10)
((a + b) * (-a / 2))

array([  0.,  -1.,  -4.,  -9., -16., -25., -36., -49., -64., -81.])

Is there more to this??

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [46]:
arr = np.random.random(20) * 20
arr

array([19.48572595,  5.55842328,  6.35632103, 16.96997661,  6.98170502,
       13.91337483, 16.60155511,  5.38265248,  9.18687205,  6.59237307,
       17.34439486,  2.50136575, 14.61323045,  8.01086471,  9.04474275,
        8.66951036,  3.69386275,  3.44803997, 16.31539645, 16.58576059])

In [47]:
arr.astype(int)

array([19,  5,  6, 16,  6, 13, 16,  5,  9,  6, 17,  2, 14,  8,  9,  8,  3,
        3, 16, 16])

In [48]:
np.floor(arr)

array([19.,  5.,  6., 16.,  6., 13., 16.,  5.,  9.,  6., 17.,  2., 14.,
        8.,  9.,  8.,  3.,  3., 16., 16.])

etc etc

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [49]:
np.random.choice(range(5), size=25).reshape(5,5)

array([[3, 2, 1, 2, 4],
       [4, 3, 2, 2, 4],
       [2, 0, 0, 2, 1],
       [0, 4, 0, 2, 2],
       [3, 2, 3, 3, 0]])

Must be more to this - maybe they mean rows should sum to 4?

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [50]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [51]:
np.linspace(0.01, 0.99, 10)

array([0.01      , 0.11888889, 0.22777778, 0.33666667, 0.44555556,
       0.55444444, 0.66333333, 0.77222222, 0.88111111, 0.99      ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [52]:
arr = np.random.random(10)
arr

array([0.65828913, 0.54049458, 0.3377628 , 0.30687553, 0.85093103,
       0.12657649, 0.53302165, 0.89360109, 0.02606166, 0.79119095])

In [53]:
arr.sort()
arr

array([0.02606166, 0.12657649, 0.30687553, 0.3377628 , 0.53302165,
       0.54049458, 0.65828913, 0.79119095, 0.85093103, 0.89360109])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [54]:
%timeit sum(np.array([3,4,5]))

821 ns ± 5.36 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [55]:
%timeit np.sum(np.array([3,4,5]))

2.05 µs ± 22.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [56]:
A, B = np.random.random(10), np.random.random(10)

In [57]:
(A == B).all()

False

#### 43. Make an array immutable (read-only) (★★☆)

In [172]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [58]:
arr = np.random.randint(0, 100, size=(10,2))
arr

array([[90,  3],
       [61,  4],
       [83, 40],
       [67, 28],
       [28, 13],
       [36, 84],
       [39, 16],
       [64, 46],
       [ 5, 78],
       [62, 96]])

In [59]:
x, y = arr[:, 0], arr[:, 1]
z = x + 1j * y
r, theta = np.abs(z), np.angle(z)
np.stack([r, theta], axis=1)

array([[9.00499861e+01, 3.33209959e-02],
       [6.11310069e+01, 6.54800249e-02],
       [9.21357694e+01, 4.49085532e-01],
       [7.26154254e+01, 3.95850441e-01],
       [3.08706981e+01, 4.34670215e-01],
       [9.13892773e+01, 1.16590454e+00],
       [4.21544778e+01, 3.89316722e-01],
       [7.88162420e+01, 6.23199330e-01],
       [7.81600921e+01, 1.50678135e+00],
       [1.14280357e+02, 9.97355801e-01]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [60]:
a = np.random.random(10)
a[a.argmax()] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [118]:
from itertools import product

arr = np.array(list(product(np.arange(0,1,0.1), np.arange(0,1,0.1))), dtype='f4,f4')

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [142]:
x, y = np.arange(5), np.arange(5)

In [156]:
np.array([[1.0 / (x_i - y_j) for y_j in y] for x_i in x])

array([[        inf, -1.        , -0.5       , -0.33333333, -0.25      ],
       [ 1.        ,         inf, -1.        , -0.5       , -0.33333333],
       [ 0.5       ,  1.        ,         inf, -1.        , -0.5       ],
       [ 0.33333333,  0.5       ,  1.        ,         inf, -1.        ],
       [ 0.25      ,  0.33333333,  0.5       ,  1.        ,         inf]])

In [157]:
# efficient method
1.0 / (x.reshape((-1,1)) - y)

array([[        inf, -1.        , -0.5       , -0.33333333, -0.25      ],
       [ 1.        ,         inf, -1.        , -0.5       , -0.33333333],
       [ 0.5       ,  1.        ,         inf, -1.        , -0.5       ],
       [ 0.33333333,  0.5       ,  1.        ,         inf, -1.        ],
       [ 0.25      ,  0.33333333,  0.5       ,  1.        ,         inf]])

[Source](https://stackoverflow.com/a/21427688/6220759)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [80]:
dtypes = [np.byte, np.ubyte, np.short, np.ushort, np.intc, np.uintc, np.int_, np.uint, np.longlong,np.ulonglong]

In [82]:
for dt in dtypes:
    info = np.iinfo(dt)
    print(dt, info.min, info.max)

<class 'numpy.int8'> -128 127
<class 'numpy.uint8'> 0 255
<class 'numpy.int16'> -32768 32767
<class 'numpy.uint16'> 0 65535
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.uint32'> 0 4294967295
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.longlong'> -9223372036854775808 9223372036854775807
<class 'numpy.ulonglong'> 0 18446744073709551615


#### 49. How to print all the values of an array? (★★☆)

In [200]:
[x for x in a]

[0.8040255864244953,
 0.6074080287098482,
 0.5962019957351188,
 0.11589170555924133,
 0.3240862851338028,
 0.41676045475780243,
 0.4134524984066579,
 0.11984348531665845,
 0.0,
 0.5783601773016271]

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [91]:
arr = np.array([8, 120, 34, 56, 234, 339, 0, 23])
val = 6

arr[np.abs(arr - val).argmin()]

8

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [161]:
np.zeros(10, dtype={'names':('x', 'y', 'r', 'g', 'b'), 'formats':('f4', 'f4', 'i4', 'i4', 'i4')})

array([(0., 0., 0, 0, 0), (0., 0., 0, 0, 0), (0., 0., 0, 0, 0),
       (0., 0., 0, 0, 0), (0., 0., 0, 0, 0), (0., 0., 0, 0, 0),
       (0., 0., 0, 0, 0), (0., 0., 0, 0, 0), (0., 0., 0, 0, 0),
       (0., 0., 0, 0, 0)],
      dtype=[('x', '<f4'), ('y', '<f4'), ('r', '<i4'), ('g', '<i4'), ('b', '<i4')])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)